/// Topic tokens that are too generic to imply real similarity between packages.
/// Used by the `alternatives` command to filter out noise when computing topic overlap.
pub const TOPIC_STOPWORDS: &[&str] = &[
    "react-native",
    "reactnative",
    "react",
    "native",
    "mobile",
    "android",
    "ios",
    "javascript",
    "typescript",
    "js",
    "ts",
    "hacktoberfest",
    "expo",
    "expo-sdk",
    "component",
    "components",
    "library",
    "module",
    "utils",
    "util",
    "helper",
    "helpers",
    "tool",
    "tools",
    "cli",
    "sdk",
];
